GET http://localhost:8080/reviews

### 

GET http://localhost:8080/reviews/1

### 

POST http://localhost:8080/reviews
Content-Type: application/json

{
    "anime": "My Hero Academia 2",
    "rating": "1",
    "content": "Meh."
}

###

PUT http://localhost:8080/reviews/13
Content-Type: application/json

{
    "anime": "My Hero ",
    "rating": "2",
    "content": "OMG SO GOOD"
}

### 

DELETE http://localhost:8080/reviews/1